### ISSUE TITLE
Memory leak

### ISSUE THREAD

**Issue by AlexBHarley** [dougmoscrop/serverless-http#153] opened 2020-04-29 21:08 UTC
Originally raised this in the [netlify cli](https://github.com/netlify/cli/issues/869) repository but I've tracked the issue down to here.

```
const express = require('express');
const serverless = require('serverless-http');

const app = express();
app.post('/.netlify/functions/index/health-check', (req, res) => {
    res.json({hello: Date.now()});
});

module.exports.handler = serverless(app);
```

Then I run the following script

```
const fetch = require('node-fetch');

(async function () {
  while (true) {
    const response = await fetch
      .default('http://localhost:8888/.netlify/functions/index/health-check', {
        method: 'POST',
        body: JSON.stringify(
          Array(500).fill({hello: 'there', date: Date.now()})
        ),
      })
      .then(x => x.json());
    console.log(response);
  }
})();
```

Consistently after ~20 seconds the process crashes with an out of memory error.

I'm _pretty_ sure that it has something to do with the ReadableStream `destroy`/`end` methods never being called but haven't been able to fix it myself.

**Comment by dougmoscrop** [comment] 2020-04-30 08:01
Yup, looks reproducible with just:

```
const serverless = require('serverless-http');

const handler = serverless((req, res) => {
    res.end('test');
});

async function run() {
    while (true) {
        await handler({
            path: '/',
            method: 'POST',
            body: 'hello'
        });
    }
}

run().catch(console.error);
```

**Comment by dougmoscrop** [comment] 2020-04-30 10:21
The problem is at least in here: https://github.com/dougmoscrop/serverless-http/blob/master/lib/response.js#L93

If I don't attach the fake-writable-stream-socket the example above works fine, but many frameworks expect to be able to write to the socket directly, so I've screwed something up in there.

The other thing I did while testing was change ServerlessRequest to have a _read() method that pushes the body only when asked rather than right away.

Also a mistake on event listener removal: https://github.com/dougmoscrop/serverless-http/blob/master/lib/finish.js#L20

![image](https://user-images.githubusercontent.com/586516/80699900-cf95dd00-8aaa-11ea-9a11-c7c5247bdf33.png)

**Comment by dougmoscrop** [comment] 2020-04-30 18:08
I could use some help ^ with whatever is going on in that onwrite bound event cycle if anybody has some time.

The "ServerResponse" class that we extend from to create the ServerlessResponse has a bunch of stuff in it that needs to be coordinated to make it look like a real server.  Changing it to use http.OutgoingMessage instead is problematic for a few reasons: there's some helper code that would need to be copied or reimplemented, and some frameworks like express, _mutate the _prototype_ of the req/res anyway (!) -- I don't have a link to the code, but if you do app.callback()(req, res) -- the res becomes a http.ServerResponse even if what you sent in is an http.OutgoingMessage - I hunted down where this was happening in the express framework at one point, but just took it as "eh, use the http.ServerResponse" and stopped caring.

So I think the best way to fix this is stick with http.ServerResponse and figure out what's happening in .assignSocket() that isn't being correctly undone?

**Comment by dougmoscrop** [comment] 2020-05-09 19:50
OK, I believe I have fixed this, but doing more testing

**Comment by dougmoscrop** [comment] 2020-05-11 07:58
Should be fixed in 2.4.0, thanks a lot for reporting this, I would appreciate if you could confirm that you no longer see the issue.

**Comment by AlexBHarley** [comment] 2020-05-11 13:52
Thanks for doing this so quickly, unfortunately just tested it out and still having trouble.

- Scenario 1 (original comment) is running with the netlify cli. And dies with an oom after 20-25 seconds
- Scenario 2 (your example) dies after ~16 seconds.

Unfortunately I don't have much more info to give you than that. I've moved towards just running an express server for development. Haven't gone live yet so I can't tell you how this would affect an actual serverless env

**Comment by dougmoscrop** [comment] 2020-05-11 15:01
What version of Node are you using?

**Comment by dougmoscrop** [comment] 2020-05-11 15:04
Ah! I see it happening in 10, but not 12. Interesting!

**Comment by AlexBHarley** [comment] 2020-05-11 17:43
Yes sorry node 10. Netlify supports Node 12 so I guess my worries there are unfounded.

**Comment by dougmoscrop** [comment] 2020-05-11 17:52
Yeah I'm not sure what the difference between 10 and 12 is, if I get cycles I can poke around, but if yo could try 2.4.1 on Node 12 that should work

**Comment by AlexBHarley** [comment] 2020-05-11 18:51
Looks like out of the two scenarios I'm trying with Node `v12.16.3`

- Scenario 1: fails in 28.629 seconds
- Scenario 2: never fails! Even tried this one with bigger payloads.

It's definitely possible there's another issue lurking somewhere with netlify's cli tool or something else I'm doing. I'd chalk this up as a win

**Comment by dougmoscrop** [comment] 2020-05-11 19:30
Okay thanks! The next time I get some cycles I will try it with netlify to see if I can spot anything.. the node http internals (and streams for that matter) involve a lot of wizardry and a lot of cross-mutation of private members so lots of ways I can see this having more issues, I tried to simplify it as best I could with a fake writable socket instead of an actual real stream, and I was feeling good about that until it didn't work with node 10!

**Comment by patrick91** [comment] 2020-09-15 09:06
I've tried the first example on aws lamdba with node 12 and didn't get memory leaks (memory got up to 100mb max) :)

**Closed** 2021-01-05 16:15 UTC
