### ISSUE TITLE
Feature Req: Expose event (and maybe context) to the request object

### ISSUE THREAD

**Issue by jeremygiberson** [dougmoscrop/serverless-http#33] opened 2017-11-26 19:46 UTC
Event can contain important information especially when utilizing custom authorizers. I recommend exposing at least the `event` on the request object so it can be accessed by middle. 

As an example, in our fork of this repo we're doing:

```javascript
// in lib/request.js
    Object.assign(this, {
      ip: event.requestContext.identity.sourceIp,
      complete: true,
      apiGateway: { event },
      httpVersion: '1.1',
      httpVersionMajor: '1',
      httpVersionMinor: '1',
      method: event.httpMethod,
      headers: headers,
      url: url.format({
        pathname: event.path,
        query: event.queryStringParameters
      })
    });
```

**Comment by dougmoscrop** [comment] 2017-11-27 16:36
You can add "middleware" transformations on req/res like this:

https://github.com/dougmoscrop/serverless-http/pull/13/files#diff-8330e164d8515979491567746e4dc5c7R118

which you can use to attach the event, context, to any key you want. does this fit your need? I'd say the issue is with lack of documentation?

**Comment by jeremygiberson** [comment] 2017-11-27 16:57
@dougmoscrop Yeah, that absolutely fits the need. It was just a lack of documentation. 

Thank you for your work on this package and making it available to the community!

**Comment by dougmoscrop** [comment] 2017-11-27 16:58
No problem! I will update the documentation and close this issue when it is done.

**Comment by evangow** [comment] 2017-12-18 22:58
After looking at the example posted above, I'm still a bit confused about how I can get serverless-http to play nice with serverless-plugin-warmup (https://github.com/FidelLimited/serverless-plugin-warmup)

In order to keep lambdas warm, but keep costs low still, serverless-plugin-warmup suggests adding some early exit logic before running lambdas like so:
``` javascript
module.exports.lambdaToWarm = function(event, context, callback) {
  /** Immediate response for WarmUP plugin */
  if (event.source === 'serverless-plugin-warmup') {
    console.log('WarmUP - Lambda is warm!')
    return callback(null, 'Lambda is warm!')
  }
  ... add lambda logic after
}
```

I see you can access the request object in your example, but this is only after running the app, right? How would you go about returning a simple callback when the source is serverless-plugin-warmup without running the (express, koa, etc.) app?

**Comment by dougmoscrop** [comment] 2017-12-19 16:03
You can do this a couple ways, but the most straightforward one would be to append to your above example:

```js
const app = koa() // etc.
const handler = serverless(app);

module.exports.lambdaToWarm = function(event, context, callback) {
  /** Immediate response for WarmUP plugin */
  if (event.source === 'serverless-plugin-warmup') {
    console.log('WarmUP - Lambda is warm!')
    return callback(null, 'Lambda is warm!')
  }
  return handler(event, context, callback);
}
```

It's all just functions!

**Comment by evangow** [comment] 2017-12-19 18:01
That makes a lot of sense! Thanks @dougmoscrop!

**Comment by dougmoscrop** [comment] 2018-01-13 17:23
I have documented the transforms in the README. Please reopen if there's anything else!

**Closed by dougmoscrop** 2018-01-13 17:23 UTC

**Comment by selected-pixel-jameson** [comment] 2019-05-28 01:52
Is this how you would go about doing this with async?

```
const handler = serverless(app)
module.exports.handler = async (event, context, callback) => {
  if (event.source === 'serverless-plugin-warmup') {
    console.log('WarmUp - Lambda is warm!')
    return callback(null, 'Lambda is Warm') 
  }

  // you can do other things here
  const result = await handler(event, context)
  // and here
  return result
}
```

**Comment by dougmoscrop** [comment] 2019-05-28 03:13
No need for callback, just return
