### ISSUE TITLE
Version 1.7.1 doesn't return a valid response for api gateway causing a 502 error "Error from Cloudfront"

### ISSUE THREAD

**Issue by rodrigomf24** [dougmoscrop/serverless-http#60] opened 2018-10-21 16:19 UTC
I had two serverless projects using nodejs + express, one locked to version `1.5.3` and the other one was using the latest version `1.7.1`. The one with the newer version was making api gateway(AWS) to return a 502 error page with the header `X-Cache: Error from Cloudfront` which is usually related to the fact that the function handler is not returning the correct response payload structure.

**Comment by dougmoscrop** [comment] 2018-10-21 17:36
Ouch, ok I'll take a look

**Comment by dougmoscrop** [comment] 2018-10-21 17:41
All my unit tests pass, and my integration tests also just passed. Can you tell me more about your deployment?

i.e.

- nodejs runtime
- web framework
- do you have any routes like ping that don't run middleware? do those work?

**Comment by dougmoscrop** [comment] 2018-10-22 02:13
I've tried this on a real-world deployment and it worked too. I need more details to be able to help.

**Comment by anthonyroach** [comment] 2018-10-22 14:35
I'm seeing the same issue in a lambda that is using Node.js 8.10 in us-east-2. The problem seems to be that the handler() is returning a promise now, so the Node.js 8.10 lambda runtime is expecting the result to be in the resolution of the promise, but the handler implementation only resolves the promise with the result when `callback` is falsey, but `callback` will never be `falsey` because the lambda runtime always provides a callback, so the promise resolves with `undefined`. 

This is the problem code:

```
        if (callback) {
          process.nextTick(() => {
            callback(null, result);
          });
        } else {
          return result;
        }
```

If you are going to return a promise, then the promise should be resolved with the result regardless of the callback being provided or not:

```
        if (callback) {
          process.nextTick(() => {
            callback(null, result);
          });
        } 
        return result;
```

**Comment by dougmoscrop** [comment] 2018-10-22 14:42
Thanks so much for the help, I have already fixed that (not knowing it was causing a problem), will release soon.

I'm also updating the integration tests to run both node6 and node8.

**Comment by anthonyroach** [comment] 2018-10-22 14:50
You're welcome. Thanks for the quick fix.

**Comment by dougmoscrop** [comment] 2018-10-22 17:55
I am so sorry for the bug, had my integration tests been running on 8.10 it would have happened (though, somehow, I did deploy a real service that works using node8.10, I will chalk it up to magic)

Please try 1.7.2. and let me know if it's fixed. Huge thanks again to @anthonyroach for tipping me off.

**Comment by dougmoscrop** [comment] 2018-10-22 17:56
- unit test added to guard against regression: https://github.com/dougmoscrop/serverless-http/blob/master/test/spec.js#L297
- integration test includes 8.10 now: https://github.com/dougmoscrop/serverless-http/blob/master/test/integration/test.js#L81

**Comment by jamiewildehk** [comment] 2018-10-23 07:35
There's nothing quite like scratching your head for 15 minutes after deploying brand new code which is giving "Malformed proxy response" errors, and then finding this thread  a mere 14 hours old.

Thanks for the quick fix @dougmoscrop ! (working fine as soon as 1.7.2 deployed)

**Comment by dougmoscrop** [comment] 2018-10-23 15:30
@rodrigomf24 if you could let me know it is fixed for you I would appreciate it

**Comment by dougmoscrop** [comment] 2018-10-25 00:36
I think differen issue

What happens when you 'node index-prod.js" ? I.e. rather than lint actually
get node to evaluate the script

**Comment by jdwolk** [comment] 2018-10-25 01:05
No output - presumably because all it's doing is setting `module.exports.handler = serverless(app)`

I also have `index-dev.js` (for executing `app.js` without `serverless-http`):

```
const app = require('./app')
const port = process.env.PORT || 7000

app.listen(port, () => console.log(`Example app listening on port ${port}!`))
```

and that works fine

**Comment by dougmoscrop** [comment] 2018-10-25 03:03
Can you put your code in a GitHub repo?

**Comment by dougmoscrop** [comment] 2018-10-26 19:52
You have a [typo](https://github.com/jdwolk/serverless-node-example/blob/master/serverless.yml#L6) that is causing your Lambda function to be deployed using the Node 4.3 runtime, which is tripping on, most likely, the async/await syntax inside Express

**Comment by jdwolk** [comment] 2018-10-26 19:53
gah. Thank you, sorry about the trouble.

**Comment by dougmoscrop** [comment] 2018-10-26 20:56
no worries. I believe this is fixed. please reopen if not.

**Closed by dougmoscrop** 2018-10-26 20:56 UTC
